import math
from datetime import datetime
from firebase_config import db  # assuming you've initialized Firebase here

def calculator(uid, label, operation, num1, num2=None):
    """
    Performs a math operation based on user input and logs it to Firebase.
    
    Parameters:
    - uid: str → Firebase user ID
    - label: str → Label for the problem (if empty, auto-generates one)
    - operation: str → '+', '-', '*', '/', '^', 'sqrt', '%', 'log10', 'ln', '!'
    - num1: float → First number (or the only input for unary operations)
    - num2: float or None → Second number (if applicable)

    Returns:
    - result of the calculation
    """
    
    # ✅ Auto-label if none provided
    if not label:
        label = f"calc_{datetime.now().strftime('%Y%m%d_%H%M')}"

    try:
        # ➕ Addition
        if operation == '+':
            result = num1 + num2

        # ➖ Subtraction
        elif operation == '-':
            result = num1 - num2

        # ✖️ Multiplication
        elif operation == '*':
            result = num1 * num2

        # ➗ Division with zero check
        elif operation == '/':
            if num2 == 0:
                return "❌ Cannot divide by zero"
            result = num1 / num2

        # ⬆️ Power
        elif operation == '^':
            result = num1 ** num2

        # ✅ Square root
        elif operation == 'sqrt':
            if num1 < 0:
                return "❌ Cannot take square root of negative number"
            result = math.sqrt(num1)

        # 📊 Percentage
        elif operation == '%':
            if num1 == 0:
                return "❌ Total value cannot be zero"
            result = (num2 / num1) * 100

        # 📈 Logarithm base 10
        elif operation == 'log10':
            if num1 <= 0:
                return "❌ log10 not defined for non-positive values"
            result = math.log10(num1)

        # 🌿 Natural log
        elif operation == 'ln':
            if num1 <= 0:
                return "❌ ln not defined for non-positive values"
            result = math.log(num1)

        # ❗ Factorial
        elif operation == '!':
            if num1 < 0 or not float(num1).is_integer():
                return "❌ Factorial only works on non-negative integers"
            result = math.factorial(int(num1))

        else:
            return "❌ Invalid operation selected"

        # ✅ Logging to Firebase
        entry = {
            "input1": num1,
            "input2": num2,
            "operation": operation,
            "result": result,
            "timestamp": datetime.now().isoformat()
        }
        db.child("users").child(uid).child("problems").child(label).set(entry)

        return result

    except Exception as e:
        return f"❌ Error: {str(e)}"
    
def run_conversion_tools(uid, value, unit_from, unit_to, label=None, save=True):
    """
    Performs unit conversion based on provided units and logs result if desired.

    Parameters:
    - uid: str → Firebase user ID
    - value: float → Input value
    - unit_from: str → Source unit
    - unit_to: str → Target unit
    - label: str → Optional label; autogenerated if blank
    - save: bool → Whether to save result to Firebase

    Returns:
    - result: float or str (error message)
    """

    try:
        if not label:
            label = f"conv_{datetime.now().strftime('%Y%m%d_%H%M')}"

        unit_from = unit_from.lower()
        unit_to = unit_to.lower()
        result = None

        # 🔥 Temperature Conversion
        if unit_from == 'c' and unit_to == 'f':
            result = value * 9/5 + 32
        elif unit_from == 'c' and unit_to == 'k':
            result = value + 273.15
        elif unit_from == 'f' and unit_to == 'c':
            result = (value - 32) * 5/9
        elif unit_from == 'f' and unit_to == 'k':
            result = (value - 32) * 5/9 + 273.15
        elif unit_from == 'k' and unit_to == 'c':
            result = value - 273.15
        elif unit_from == 'k' and unit_to == 'f':
            result = (value - 273.15) * 9/5 + 32

        # 🔥 Pressure Conversion
        elif unit_from == 'atm' and unit_to == 'pascal':
            result = value * 101325
        elif unit_from == 'atm' and unit_to == 'mmhg':
            result = value * 760
        elif unit_from == 'pascal' and unit_to == 'atm':
            result = value / 101325
        elif unit_from == 'pascal' and unit_to == 'mmhg':
            result = value / 133.322
        elif unit_from == 'mmhg' and unit_to == 'atm':
            result = value / 760
        elif unit_from == 'mmhg' and unit_to == 'pascal':
            result = value * 133.322

        # 🔥 Energy Conversion
        elif unit_from == 'j' and unit_to == 'cal':
            result = value / 4.184
        elif unit_from == 'cal' and unit_to == 'j':
            result = value * 4.184

        # 🔥 Mass ↔ Moles via molar mass
        elif unit_from == 'g' and unit_to == 'mol':
            return "❌ Please provide molar mass for this conversion."
        elif unit_from == 'mol' and unit_to == 'g':
            return "❌ Please provide molar mass to convert mol to grams."

        # 🔥 Length Conversion
        elif unit_from == 'km' and unit_to == 'm':
            result = value * 1000
        elif unit_from == 'm' and unit_to == 'km':
            result = value / 1000
        elif unit_from == 'cm' and unit_to == 'm':
            result = value / 100
        elif unit_from == 'm' and unit_to == 'cm':
            result = value * 100
        elif unit_from == 'mm' and unit_to == 'cm':
            result = value / 10
        elif unit_from == 'cm' and unit_to == 'mm':
            result = value * 10
        elif unit_from == 'um' and unit_to == 'mm':
            result = value / 1000
        elif unit_from == 'mm' and unit_to == 'um':
            result = value * 1000

        # 🔥 Weight Conversion
        elif unit_from == 'kg' and unit_to == 'g':
            result = value * 1000
        elif unit_from == 'g' and unit_to == 'kg':
            result = value / 1000
        elif unit_from == 'mg' and unit_to == 'g':
            result = value / 1000
        elif unit_from == 'g' and unit_to == 'mg':
            result = value * 1000
        elif unit_from == 'ug' and unit_to == 'g':
            result = value / 1e6
        elif unit_from == 'g' and unit_to == 'ug':
            result = value * 1e6

        # 🔥 Radians ↔ Degrees
        elif unit_from == 'rad' and unit_to == 'deg':
            result = value * (180 / math.pi)
        elif unit_from == 'deg' and unit_to == 'rad':
            result = value * (math.pi / 180)

        else:
            return f"❌ Unsupported conversion: {unit_from} → {unit_to}"

        # ✅ Optional logging to Firebase
        if save:
            data = {
                "value": value,
                "from_unit": unit_from,
                "to_unit": unit_to,
                "converted_result": result,
                "timestamp": datetime.now().isoformat()
            }
            db.child("users").child(uid).child("conversions").child(label).set(data)

        return result

    except Exception as e:
        return f"❌ Error during conversion: {str(e)}"
    
    
def view_saved_problems(uid):
    """
    Returns a dictionary of saved problems for a given UID.
    Used by HistoryScreen to render in GUI.
    """
    try:
        problems = db.child("users").child(uid).child("problems").get()
        if not problems.each():
            return {}

        # Convert to dictionary
        saved_data = {}
        for item in problems.each():
            label = item.key()
            details = item.val()
            saved_data[label] = details
        return saved_data

    except Exception as e:
        return f"❌ Error retrieving problems: {str(e)}"